from __future__ import annotations

from collections.abc import AsyncGenerator

import httpx

from app.core.config import get_settings
from app.core.logging import get_logger
from app.services.tts.base import TTSProvider

_logger = get_logger(__name__)
_settings = get_settings()

# Available OpenAI TTS voices
VOICES = {"alloy", "echo", "fable", "nova", "onyx", "shimmer"}
# Available models
MODELS = {"tts-1", "tts-1-hd"}


class OpenAITTSProvider(TTSProvider):
    """
    Real OpenAI Text-to-Speech provider.
    Uses the /audio/speech endpoint.
    Model: tts-1 (low latency) or tts-1-hd (higher quality).
    Returns MP3 audio at 24 kHz.
    """

    def __init__(
        self,
        voice: str | None = None,
        model: str = "tts-1",
    ) -> None:
        self._voice = (voice or _settings.tts_voice).lower()
        if self._voice not in VOICES:
            _logger.warning("Unknown TTS voice '%s', falling back to 'nova'", self._voice)
            self._voice = "nova"

        self._model = model if model in MODELS else "tts-1"

        self._client = httpx.AsyncClient(
            base_url="https://api.openai.com/v1",
            headers={"Authorization": f"Bearer {_settings.openai_api_key}"},
            timeout=60.0,
        )

    async def synthesize(self, text: str) -> bytes:
        """Convert text to MP3 audio bytes. Returns full audio."""
        if not text or not text.strip():
            return b""

        # OpenAI TTS max input length is 4096 characters
        text = text.strip()[:4096]
        _logger.info(
            "TTS synthesize: model=%s voice=%s len=%d",
            self._model,
            self._voice,
            len(text),
        )

        try:
            resp = await self._client.post(
                "/audio/speech",
                json={
                    "model": self._model,
                    "input": text,
                    "voice": self._voice,
                    "response_format": "mp3",
                },
            )
            resp.raise_for_status()
            audio_bytes = resp.content
            _logger.info("TTS complete: %d bytes", len(audio_bytes))
            return audio_bytes

        except httpx.HTTPStatusError as exc:
            _logger.error(
                "OpenAI TTS API error %d: %s",
                exc.response.status_code,
                exc.response.text,
            )
            raise
        except Exception as exc:
            _logger.error("OpenAI TTS synthesis failed: %s", exc)
            raise

    async def synthesize_stream(self, text: str) -> AsyncGenerator[bytes, None]:
        """Stream MP3 audio bytes as they are generated by OpenAI."""
        if not text or not text.strip():
            return

        text = text.strip()[:4096]
        _logger.info("TTS stream: voice=%s len=%d", self._voice, len(text))

        try:
            async with self._client.stream(
                "POST",
                "/audio/speech",
                json={
                    "model": self._model,
                    "input": text,
                    "voice": self._voice,
                    "response_format": "mp3",
                },
            ) as resp:
                resp.raise_for_status()
                async for chunk in resp.aiter_bytes(chunk_size=4096):
                    if chunk:
                        yield chunk
        except Exception as exc:
            _logger.error("OpenAI TTS stream failed: %s", exc)
            raise

    @property
    def audio_format(self) -> str:
        return "mp3"

    @property
    def sample_rate(self) -> int:
        return 24000

    async def close(self) -> None:
        await self._client.aclose()
